### ISSUE TITLE
Pre-download images

### ISSUE THREAD

**Issue by calizilla** [Sydney-Informatics-Hub/Germline-StructuralV-nf#63]
Copyq has maximum walltime of 10 hours. I would like to be able to pull the containers first using copyq, and then run the head job on the normal queue. Similar to nf-core download tool, or a test profile perhaps.

**Comment by georgiesamaha** [comment]
`pullContainers.sh` does this and is included in `nextflow.config` but hashed out (oops). Needs to be unhashed.

**Comment by georgiesamaha** [comment]
@chlu0571 things to try resolve inconsistency between nextflow and manual run of `pullContainer.sh`:

- [ ] Try rename containers in `nextflow.config`, empty cache and run workflow 
- [ ] Test the application of singularity cache variables are being applied correctly (see issue #64)
