### ISSUE TITLE
pullContainers.sh not utilising specified cachedir 

### ISSUE THREAD

**Issue by calizilla** [Sydney-Informatics-Hub/Germline-StructuralV-nf#64]
Job fails with:

```
Job <jobID> killed due to exceeding jobfs quota
```

Script needs the following line added:

```
export SINGULARITY_TMPDIR=<existing-dir>
```

OR, instructions in README for user to set `SINGULARITY_TMPDIR` in `~/.bashrc`

**Comment by georgiesamaha** [comment]
Can you provide some more context about why tmpdir is needed, the command you executed and samples you were running on? Can't currently replicate this.

**Comment by calizilla** [comment]
The default SINGULARITY_TMPDIR location is user's home. Home on Gadi is 10 GB (and probably similarly capped on some other infrastructures) so it fills up and then encounters disk quota exceeded error. If you have SINGULARITY_TMPDIR set in your bashrc, this may explain why you are unable to replicate.
