### ISSUE TITLE
Inconsistent parameter definition and application for gadi account

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/Germline-StructuralV-nf#65]
Project account has been defined and applied inconsistently between `nextflow.config` and `configs/gadi.config`: 

In nextflow.config it is defined as: 
```
gadi_account = false
```

In gadi.config, it is applied as: 
```
storage = "scratch/${params.pbs_account}+gdata/${params.pbs_account}"
```

storage variable needs to call the correct parameter as defined in nextflow.config. Currently failing to apply correct storage access permissions.

**Comment by chlu0571** [comment]
the mix up of pbs & gadi account were fixed by modifying on pbs script in scripts & gadi.config in config directories
